### ISSUE TITLE
Slider won't work on Light group

### ISSUE THREAD

**Issue by PCR-2020** [tonyflowed/dimmer-button#4]
I love this custom button, thanks! (Only downside I could find so far, is that you can't scroll up and down on your phone, if you're touching the button)

However when I group some lights together, which are both dimmable, I can only turn on and off ?

**Comment by tonyflowed** [comment]
Supported features seems to have been a bit unreliable, removed them from the latest version.
All lights default to toggle now but you should be able to set the mode to anything.

Unless you're using vertical buttons scrolling should be working🤔

**Comment by PCR-2020** [comment]
Could get this to work, so needed to switch back to https://github.com/thomasloven/lovelace-slider-entity-row, because of the (light) groups behavior. Really loved the graphics of this customization though. Using pictures of the lights is massively easier for the users.
